### ISSUE TITLE
[HW/핸들러] 인터럽트 핸들러 만들기

### ISSUE THREAD

**Issue by KimYC1223** [KimYC1223/KAU_HW_2018#1]
진행상황 보고해주세요

**Comment by KimYC1223** [comment]
인터럽트 핸들러로 받아올 것들

키 인터럽트 & GPIO 인터럽트

민우 ( @b727dlalsdn ) 는 GPIO 인터럽트가 되는지 확인해보기

**Comment by b727dlalsdn** [comment]
http://www-ug.eecg.utoronto.ca/desl/nios_devices_SoC/dev_pit.html
GPIO address값,  ctrl register 값, assembler랑 C언어 예제 코드입니다!

**Comment by b727dlalsdn** [comment]
GPIO 포트는 2개로 GPIO0 = JP1  ( 0xFF200060) , GPIO1 = JP2 (0xFF200070)임
Address map:
base : pin에 데이터를 쓰거나 pin의 데이터를 받아오는 data 레지스터

base + 4 : 0으로 설정하면 input이고 1으로 설정하면 output으로 Direction 레지스터를 뜻한다.(0xFFFFFFFF이면 모든 핀(32bit)를 output으로 사용한다는 것)
 
base + 8 : interrupt mask bit로 모두 사용할 꺼면 0xFFFFFFFF으로 한다.

base + 12 : edge capture bit로 해당 비트를 1로 설정하거나 0xFFFFFFFF으로 모든 비트를 clear 한다. 

NIOS2에서 JP1 Expansion parallel port의 IRQ는 11이고  JP2 Expansion parallel port의 IRQ는 12이다.
C언어에서 NIOS2 인터럽트 설정시 TO와 KEY도 받기 때문에 IRQ를 0 , 1 , 11 ,12를 enable 해주면 됨
