### ISSUE TITLE
[HW/기타] 재료 구매하기

### ISSUE THREAD

**Issue by KimYC1223** [KimYC1223/KAU_HW_2018#5]
생각중

**Comment by KimYC1223** [comment]
![image](https://user-images.githubusercontent.com/40852277/48642538-7d7d0b00-ea20-11e8-81d3-df5ce6d16c64.png)


일단 생각난것만 적은거임... 혹시 본인이 더 구매하고 싶은게 있다면 이슈에 추가할 것!

나는 아직 덜 구매한 상태임

현재까지 금액 36,476원

**Comment by b727dlalsdn** [comment]
혹시 사이트 링크 보내주실수 있나요~

**Comment by KimYC1223** [comment]
http://www.devicemart.co.kr/

**Comment by b727dlalsdn** [comment]
본체에는 빵판에 콘센트에 릴레이 연결해서 꽂고 GPIO에서 VCC랑 GND만 꽂고 컨트롤러에서 오는 값을 읽을 수 있게 AND나 OR게이트를 사용하면 되는거여서 컨트롤러의 값을 읽어와서 컨트롤러가 1이면 값이 들어가도록 하게 AND게이트가 있으면 좋을 것 같네요!
AND의 한 단자에는 1을 항상 주고 남은 단자에는 컨트롤러에서 오는 값을 불러와 0이면 안되고 1이여야지 작동하게 하기 위해서 AND게이트가 있어야 할 것 같아요 갯수는 3개(각각의 입력) + X(기능값들)요!

**Comment by KimYC1223** [comment]
구매 완료하였음
