### ISSUE TITLE
[HW/그래픽] VGA에 숫자 출력하기

### ISSUE THREAD

**Issue by KimYC1223** [KimYC1223/KAU_HW_2018#6]
지정된 위치에 지정된 숫자를 출력하는 함수 만들기

그리고 그를 이용하여 지정된 위치에 지정된 두 자리 숫자를 출력하는 함수 만들기

**Comment by KimYC1223** [comment]
일을 했으면 이슈에 적어주세요

**Comment by b727dlalsdn** [comment]
완료
현재 모니터에 굵은 글씨로 0에서9까지는 VGA에 나타냄
IF문을 사용해 입력에 따라 0에서9를 나타내는 IF문을 들어감

할 일
10의 자리인 경우 10의 자리와 1의 자리를 나눠서 각각 좌표에 나타내야함
 입력 값을 입력하면 그 숫자가 모니터에 나와야함
 정적인 것이 아니라 동적으로 VGA에 타이머가 나타나야함

**Comment by b727dlalsdn** [comment]
현재상황 : 코드를 완성하고 compile & load했지만 모니터에 나오지 조차 않음.
문제점 : 0~9숫자의 bit map을 header file로 사용해서 main에서 참조를 했는데 불러오는 과정에서 문제가 생겼다고 판단.
해야할 일 : main에 bit map을 void함수로 선언해서 header file이 아닌 main에 포함시키는 방향으로 수정해보기!

**Comment by b727dlalsdn** [comment]
git hub에 monitor_timer을 올려놨습니다. 아직 완성본은 아니며,
tes1은 0~9까지의 숫자의 bit map을 헤더파일로 저장해 사용한 방법이고,
test2는 헤더파일을 사용하지 않고 메인이 되는 파일에 합쳐놓은 파일입니다.
practice는 연습용이니 확인 안하셔도 됩니다!

**Comment by b727dlalsdn** [comment]
현재 동방에서 올려놓은 test1 (use header) 와 test2 (not use header) 둘다 보드에 올려놓은 결과 timer가 모니터에 잘 나오며, 00초가 되면 멈추도록 했습니다. 또한 이제 key interrupt에 따라 on/off를 모니터에 나타내도록 하겠습니다.

**Comment by b727dlalsdn** [comment]
monitor_timer의 하위폴더 test_timer_state_demo를 추가했습니다.
이는 12.4일 데모받을 모니터입니다.
key0 : port1 on하고 timer 시작
key1 : port2 on하고 timer 시작
key2 : port3 on하고 timer 시작
key3 : 
sw0이 1인 경우 port1 timer 10증가
sw1이 1인 경우 port2 timer 10증가
sw2이 1인 경우 port3 timer 10증가
sw3이 1인 경우 sw0~2중 high값인 경우 0으로 초기화
