### ISSUE TITLE
[HW / 보고서] 회의록 1

### ISSUE THREAD

**Issue by b727dlalsdn** [KimYC1223/KAU_HW_2018#7]
회의록 1 작성해놓은거 혹시 몰라서 따로 저장해놨고,
 제가 작성한 부분 줄이고 그림이나 표는 삭제했습니다. 작성하신 부분에서 1페이지 이내로 만들기 위해 지울 수 있는 부분은 지워주세요!

**Comment by KimYC1223** [comment]
확인하고 수정한다음 git push 하였습니다.
